### ISSUE TITLE
Compression of BMP image (24bit)

### ISSUE THREAD

**Issue by kamina-san** [WangXuan95/Hard-JPEG-LS#4]
Hello and thank you very much for the core!

Do you believe it would be easy to compress a 24bit BMP image with changes in the core?
or would it be a pretty arduous or even impossible task?
Also if it is not possible, would you happen to know of any free IP core that could do that?

Thank you very much for you time and congrats for the great work!!

**Comment by WangXuan95** [comment]
There are no technical barriers to realizing an FPGA-based JPEG-LS RGB image encoder. The JPEG-LS specification also supports RGB image format (see https://www.itu.int/rec/T-REC-T.87/en).

However, I only designed a version that outputs grayscale JPEG-LS formats. 

If you want to compress RGB image, there may be 3 solutions:

* Design an FPGA-based RGB image encoder that follows the JPEG-LS specification by yourself. The core algorithm is the same as that of grayscale, but the packaging format is different, so you may need to spend a lot of work. In this way, my design can only provide a reference.

* Separate the three RGB channels into three independent grayscale images and compress them using my design. In this way, you need to spend the least amount of work, but it's not very elegant.

* Purchase other IPs, e.g., from CAST Inc. As far as I know, there seems no open-sourced FPGA-based JPEG-LS RGB image encoder.

That you for liking my design. If you think it is good, please star it!

**Comment by kamina-san** [comment]
Thx for the thorough reply! I starred it of course and it is possible that I will try to build on your design to implement what I need.
